FROM python:3.10

# 设置工作目录
WORKDIR /code

# 设置时区
RUN rm /etc/localtime
RUN ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# 安装依赖
COPY requirements.txt /code/requirements.txt
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip config set global.extra-index-url "http://mirrors.aliyun.com/pypi/simple/ https://pypi.mirrors.ustc.edu.cn/simple/ http://pypi.hustunique.com/ http://pypi.douban.com/simple/ http://pypi.sdutlinux.org/"
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
# RUN apt-get update && apt-get install -y nano
